# Comparison for LogSumExp

In [1]:
import numpy as np
import torch
import scipy
from scipy import signal

In [2]:
a = np.random.uniform(size = (10,))
b = np.random.uniform(size = (3,))

In [3]:
c = signal.fftconvolve(a,b)
c.shape, c

((12,), array([0.65250472, 0.83769398, 1.03563552, 1.00901556, 1.27376797,
        1.46376657, 0.89938565, 0.76974469, 0.94633292, 1.27620939,
        0.80020662, 0.37612405]))

In [4]:
b1 = torch.flip(torch.tensor(b), (0,)).view(1, 1, -1)
c = torch.nn.functional.conv1d(torch.tensor(a).view(1,1,-1), b1, padding = len(b) - 1).numpy()
c.shape, c

((1, 1, 12),
 array([[[0.65250472, 0.83769398, 1.03563552, 1.00901556, 1.27376797,
          1.46376657, 0.89938565, 0.76974469, 0.94633292, 1.27620939,
          0.80020662, 0.37612405]]]))

In [5]:
b1.view(-1).numpy()

array([0.42696145, 0.44215837, 0.75741494])

In [6]:
c = torch.nn.functional.conv1d(torch.tensor(a).view(1,1,-1), torch.tensor(b).view(1,1,-1), padding = len(b) - 1).numpy()
c.shape, c

((1, 1, 12),
 array([[[0.36782264, 0.63840516, 1.14529613, 0.98259342, 1.12348075,
          1.3679907 , 1.20335495, 0.94908097, 0.6498084 , 1.12725285,
          1.11807052, 0.66723114]]]))

In [7]:
a = np.array([1, 1, 1, 1, 1, 1])
b = np.array([1, 2, 3])

In [8]:
signal.fftconvolve(a, b)

array([1., 3., 6., 6., 6., 6., 5., 3.])

In [9]:
torch.nn.functional.conv1d(torch.tensor(a).view(1,1,-1), torch.tensor(b).view(1,1,-1), padding = len(b) - 1).view(-1).numpy()

array([3, 5, 6, 6, 6, 6, 3, 1])